# things to update
tc_path: ~/mortazavi_lab/bin/TranscriptClean/


ref:
  fa_link: https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz
  fa_gz: ref/genome.fa.gz
  fa: ref/genome.fa
  gtf_link: https://www.encodeproject.org/files/gencode.vM21.primary_assembly.annotation_UCSC_names/@@download/gencode.vM21.primary_assembly.annotation_UCSC_names.gtf.gz
  gtf_gz: ref/annot.gtf.gz
  gtf: ref/annot.gtf
  sjs: ref/annot_junc.bed
  talon_db: ref/ref_talon.db

data:
  # fastq: data/{batch}/raw/{dataset}.fastq

  map_stats: data/{batch}/minimap2/{dataset}_map_stats.txt
  sam: data/{batch}/minimap2/{dataset}.sam
  bam: data/{batch}/minimap2/{dataset}.bam
  sam_log: data/{batch}/minimap2/{dataset}_minimap.log
  sam_rev: data/{batch}/minimap2/{dataset}.rev.sam

  sam_clean: data/{batch}/tc/{dataset}_clean.sam
  tc_stats: data/{batch}/tc/{dataset}_tc_stats.txt

  sam_label: data/{batch}/talon/{dataset}_labeled.sam
  talon_config: data/{batch}/talon/talon_config.csv
  talon_db: data/{batch}/talon/annot_talon.db
