ref:
  gtf_ver: 'vM21'
  gtf_link: https://www.encodeproject.org/files/gencode.vM21.primary_assembly.annotation_UCSC_names/@@download/gencode.vM21.primary_assembly.annotation_UCSC_names.gtf.gz
  fa_ver: 'mm10'
  fa_link: https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz

  gtf_gz: ref/annot.gtf.gz
  gtf: ref/annot.gtf
  gtf_utr: ref/annot_utr.gtf
  sjs: ref/annot_junc.bed

  fa_gz: ref/ref.fa.gz
  fa: ref/ref.fa
  chrom_sizes: ref/chrom_sizes.txt

  # LAPA reference - ENCODE refs + GENCODE UTRs
  lapa:
    gtf: ref/{species}/lapa/ref.gtf

  # cerberus references - mouse cerberus annotation from
  # the long read ENCODE4 RNA project
  cerberus:
    ca_link: https://www.encodeproject.org/files/ENCFF999KXH/@@download/ENCFF999KXH.h5
    ca: ref/ca.h5
    ca_ends: ref/ca_{end_mode}.bed
    ca_ics: ref/ca_ic.tsv
    ca_annot: ref/ca_annot.h5

map:
  sam: data/minimap2/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}.sam
  log: data/minimap2/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_minimap.log
  stats: data/minimap2/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_minimap_stats.txt
  sam_rev: data/minimap2/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_reverse.sam

tc:
  path: ~/mortazavi_lab/bin/TranscriptClean/
  min_intron_size: 21

  sam: data/tc/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_clean.sam
  fa: data/tc/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_clean.fa
  log: data/tc/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_clean.log
  te_log: data/tc/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_clean.TE.log
  stats: data/tc/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_tc_stats.txt

talon:
  frac_a_range: 20
  sam: data/talon/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_labeled.sam
