human_ref:
  gtf_ver: 'v29'
  gtf_link: https://www.encodeproject.org/files/gencode.v29.primary_assembly.annotation_UCSC_names/@@download/gencode.v29.primary_assembly.annotation_UCSC_names.gtf.gz

  fa_ver: 'hg38'
  fa_link: https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz

  gtf_gz: human_ref/annot.gtf.gz
  gtf: human_ref/annot.gtf

  t_fa_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.transcripts.fa.gz
  t_fa_gz: human_ref/annot.fa.gz
  t_fa: human_ref/annot.fa

  all_gtf_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.chr_patch_hapl_scaff.annotation.gtf.gz
  all_gtf_gz: human_ref/all_annot.gtf.gz
  all_gtf: human_ref/all_annot.gtf

  fa_gz: human_ref/ref.fa.gz
  fa: human_ref/ref.fa

ref:
  gtf_ver: 'vM21'
  gtf_link: https://www.encodeproject.org/files/gencode.vM21.primary_assembly.annotation_UCSC_names/@@download/gencode.vM21.primary_assembly.annotation_UCSC_names.gtf.gz
  fa_ver: 'mm10'
  fa_link: https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz

  t_fa_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M21/gencode.vM21.transcripts.fa.gz
  t_fa_gz: ref/annot.fa.gz
  t_fa: ref/annot.fa

  gtf_gz: ref/annot.gtf.gz
  gtf: ref/annot.gtf
  gtf_utr: ref/annot_utr.gtf
  sjs: ref/annot_junc.bed

  fa_gz: ref/ref.fa.gz
  fa: ref/ref.fa

  pseudochrom:
    fa: ref/pseudochrom/{pseudochrom}/ref.fa
    gtf: ref/pseudochrom/{pseudochrom}/annot.gtf

    gene:
      fq: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_t.fastq
      sam: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_mapped.sam
      log: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_minimap.log
      tc_sam: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_clean.sam
      tc_fa: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_clean.fa
      tc_log: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_clean.log
      te_log: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_clean.TE.log

      bam: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_mapped.bam
      sort_bam: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_mapped_sorted.bam
      ind_bam: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_mapped_sorted.bam.bai

      config: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_config.csv
      db: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_ref_talon.db
      gtf: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_talon_observedOnly.gtf
      fmt_gtf: ref/pseudochrom/{pseudochrom}/{mouse_gene}/{mouse_gene}_fmt.gtf

    human_gene:
      fq: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_t.fastq
      sam: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_mapped.sam
      log: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_minimap.log
      tc_sam: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_clean.sam
      tc_fa: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_clean.fa
      tc_log: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_clean.log
      te_log: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_clean.TE.log

      bam: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_mapped.bam
      sort_bam: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_mapped_sorted.bam
      ind_bam: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_mapped_sorted.bam.bai

      config: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_config.csv
      db: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_ref_talon.db
      gtf: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_talon_observedOnly.gtf
      fmt_gtf: human_ref/pseudochrom/{pseudochrom}/{human_gene}/{human_gene}_fmt.gtf


    fa_merge: ref/genome/{genotype}/merged.fa
    gtf_merge: ref/genome/{genotype}/annot.gtf
    chrom_sizes: ref/genome/{genotype}/chrom_sizes.txt
    db: ref/genome/{genotype}/ref.db

    talon:
      # reference to use for humanized insertions
      db: ref/talon/{genotype}/ref.db


  # talon reference -- db from the input gtf
  talon:
    db: ref/talon/ref.db

  # LAPA reference - ENCODE refs + GENCODE UTRs
  lapa:
    gtf: ref/lapa/ref.gtf

  # cerberus references - mouse cerberus annotation from
  # the long read ENCODE4 RNA project
  cerberus:
    link: https://www.encodeproject.org/files/ENCFF999KXH/@@download/ENCFF999KXH.h5
    ca: ref/ca.h5
    ends: ref/ca_{end_mode}.bed
    ics: ref/ca_ic.tsv
    ca_annot: ref/ca_annot.h5
    gtf: ref/cerberus.gtf


map:
  sam: ad008_hac/data/minimap2/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}.sam
  log: ad008_hac/data/minimap2/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_minimap.log
  stats: ad008_hac/data/minimap2/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_minimap_stats.txt
  sam_rev: ad008_hac/data/minimap2/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_reverse.sam

tc:
  path: ~/mortazavi_lab/bin/TranscriptClean/
  min_intron_size: 21

  sam: ad008_hac/data/tc/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_clean.sam
  fa: ad008_hac/data/tc/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_clean.fa
  log: ad008_hac/data/tc/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_clean.log
  te_log: ad008_hac/data/tc/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_clean.TE.log
  stats: ad008_hac/data/tc/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_tc_stats.txt

talon_label:
  frac_a_range: 20
  sam: ad008_hac/data/talon_label/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_labeled.sam
  bam: ad008_hac/data/talon_label/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_labeled.bam
  sort_bam: ad008_hac/data/talon_label/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_labeled_sorted.bam
  ind_bam: ad008_hac/data/talon_label/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{flowcell}_labeled_sorted.bam.bai

merge:
  bam: ad008_hac/data/merge/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}.bam
  sort_bam: ad008_hac/data/merge/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_sorted.bam
  ind_bam: ad008_hac/data/merge/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_sorted.bam.bai
  bw: ad008_hac/data/merge/{study}/{genotype}_{sex}_{age}_{tissue}_{biorep_num}_{strand}.bw

# run talon on bioreplicates so that reproducibility
# metrics for novel isoforms are biologically meaningful
talon:
  min_transcript_len: 0
  max_5_dist: 500
  max_3_dist: 300
  max_frac_a: 0.5
  min_count: 5
  min_datasets: 2

  config: ad008_hac/data/talon/{study}/{genotype}_{sex}_{age}_{tissue}_config.csv
  db: ad008_hac/data/talon/{study}/{genotype}_{sex}_{age}_{tissue}_talon.db
  temp_dir: ad008_hac/data/talon/{study}/{genotype}_{sex}_{age}_{tissue}_temp/
  annot: ad008_hac/data/talon/{study}/{genotype}_{sex}_{age}_{tissue}_talon_read_annot.tsv
  pass_list: ad008_hac/data/talon/{study}/{genotype}_{sex}_{age}_{tissue}_pass_list.csv
  ab: ad008_hac/data/talon/{study}/{genotype}_{sex}_{age}_{tissue}_unfilt_talon_abundance.tsv
  filt_ab: ad008_hac/data/talon/{study}/{genotype}_{sex}_{age}_{tissue}_talon_abundance_filtered.tsv
  gtf: ad008_hac/data/talon/{study}/{genotype}_{sex}_{age}_{tissue}_talon.gtf

# similarly, run lapa on bioreplicates
lapa:
  config: ad008_hac/data/lapa/{study}/{genotype}_{sex}_{age}_{tissue}/config.csv
  ends: ad008_hac/data/lapa/{study}/{genotype}_{sex}_{age}_{tissue}/{end_mode}/clusters.bed
  links: ad008_hac/data/lapa/{study}/{genotype}_{sex}_{age}_{tissue}/tss_to_tes_links.csv

  corrected:
    gtf: ad008_hac/data/lapa/{study}/{genotype}_{sex}_{age}_{tissue}/talon_corrected/corrected.gtf
    filt_ab: ad008_hac/data/lapa/{study}/{genotype}_{sex}_{age}_{tissue}/talon_corrected/filtered_abundance_corrected.tsv

  filt:
    t_novs: ['Known', 'NIC', 'NNC', 'ISM_rescue']
    g_novs: ['Known', 'Intergenic', 'Fusion']
    remove_spikes: True

    pass_list: ad008_hac/data/lapa/{study}/{genotype}_{sex}_{age}_{tissue}/pass_list.tsv
    filt_ab: ad008_hac/data/lapa/{study}/{genotype}_{sex}_{age}_{tissue}/filtered_abundance.tsv
    gtf: ad008_hac/data/lapa/{study}/{genotype}_{sex}_{age}_{tissue}/filtered.gtf

    sort_gtf: ad008_hac/data/lapa/{study}/{genotype}_{sex}_{age}_{tissue}/filtered.sorted.gtf
    ind_gtf: ad008_hac/data/lapa/{study}/{genotype}_{sex}_{age}_{tissue}/filtered.sorted.gtf.idx

# TODO - how to run cerberus?
cerberus:
  tss:
    dist: 50
    slack: 50
    agg_slack: 20
  tes:
    dist: 50
    slack: 50
    agg_slack: 20
  ics: ad008_hac/data/cerberus/{study}/{genotype}_{sex}_{age}_{tissue}_{cerberus_run}_ic.tsv
  ends: ad008_hac/data/cerberus/{study}/{genotype}_{sex}_{age}_{tissue}_{cerberus_run}_{end_mode}.bed

  ca: ad008_hac/data/cerberus/{study}/{genotype}_{sex}_{age}_{tissue}_{cerberus_run}.h5
  ca_annot: ad008_hac/data/cerberus/{study}/{genotype}_{sex}_{age}_{tissue}_{cerberus_run}_annot.h5
  gtf: ad008_hac/data/cerberus/{study}/{genotype}_{sex}_{age}_{tissue}_{cerberus_run}.gtf
  ab: ad008_hac/data/cerberus/{study}/{genotype}_{sex}_{age}_{tissue}_{cerberus_run}_abundance.tsv

  agg:
    tss:
      slack: 20
    tes:
      slack: 20
    ics: ad008_hac/data/cerberus/agg/{study}_{genotype}_{sex}_{age}_{tissue}_{cerberus_run}_ic.tsv
    ends: ad008_hac/data/cerberus/agg/{study}_{genotype}_{sex}_{age}_{tissue}_{cerberus_run}_{end_mode}.bed
